/*Find the total revenue generated by each employee*/

SELECT employee_id, SUM(quantity* unit_price) AS revenue  FROM order_details od 
JOIN orders o on od.order_id = o.order_id
GROUP BY employee_id;
